// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R9RrUyWB7zxA_MWkPbDj4G4gk43BNb0',
    appId: '1:629086388660:web:9be208463f8b52bfa572e1',
    messagingSenderId: '629086388660',
    projectId: 'ask-meu',
    authDomain: 'ask-meu.firebaseapp.com',
    storageBucket: 'ask-meu.firebasestorage.app',
    measurementId: 'G-WW6B2T0C6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKkJj6bZ6tlDHFiCiEg69stKttVS-YXhU',
    appId: '1:629086388660:android:20246fb8be41b7cda572e1',
    messagingSenderId: '629086388660',
    projectId: 'ask-meu',
    storageBucket: 'ask-meu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZxV64rOMiLBfz7rTBDlURZiYc4qw4jk',
    appId: '1:629086388660:ios:51995b0c80c25bc7a572e1',
    messagingSenderId: '629086388660',
    projectId: 'ask-meu',
    storageBucket: 'ask-meu.firebasestorage.app',
    iosBundleId: 'com.example.askMeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZxV64rOMiLBfz7rTBDlURZiYc4qw4jk',
    appId: '1:629086388660:ios:51995b0c80c25bc7a572e1',
    messagingSenderId: '629086388660',
    projectId: 'ask-meu',
    storageBucket: 'ask-meu.firebasestorage.app',
    iosBundleId: 'com.example.askMeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3R9RrUyWB7zxA_MWkPbDj4G4gk43BNb0',
    appId: '1:629086388660:web:de94c77a94728b43a572e1',
    messagingSenderId: '629086388660',
    projectId: 'ask-meu',
    authDomain: 'ask-meu.firebaseapp.com',
    storageBucket: 'ask-meu.firebasestorage.app',
    measurementId: 'G-28QR0XK9GF',
  );
}
